{"uuid": "95a6113c-3e56-4181-a57e-fa8c2e851959", "children": ["7254d574-eb91-4138-8372-de36299c9f52"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: New session attempts retry count exceeded\n\n", "trace": "  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 72, in driver\n    browser = get_driver(config, download_dir=temp_dir)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 53, in get_driver\n    browser = webdriver.Remote(selenoid, desired_capabilities=capabilities)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 359, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Init browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: New session attempts retry count exceeded\n\n", "trace": "  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 72, in driver\n    browser = get_driver(config, download_dir=temp_dir)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 53, in get_driver\n    browser = webdriver.Remote(selenoid, desired_capabilities=capabilities)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 359, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1640021900678, "stop": 1640021977924}], "start": 1640021900678, "stop": 1640021978040}], "start": 1640021900678, "stop": 1640021979058}