{"uuid": "7ea8cdb4-e63f-451e-baea-048648187607", "children": ["6c90382b-3038-43c7-85b5-3d93e7e33218", "dc1dcf29-2220-45c9-bd4b-2fc2343fbcdd", "3288b5fe-5b53-4410-9442-aded9b799f66", "1e80b358-bc8d-45a5-9128-061dd142b0b6", "59d2cd20-6534-4d73-b6e9-361b4e16a001", "56c9a484-069a-4b07-a3a2-0780c0332328", "2e69fe6e-5270-45a0-8304-febd729dd167", "b24495b7-67fb-493c-83c1-86f2d71bb92c", "e4f1f0e9-60de-4343-b9b7-06df4d0a4b69", "08b8d85e-0360-4ab4-8162-a4ccfc830a2d", "7e247a8e-315e-47ca-be03-e5a42f187307", "e13b1a14-85e6-4d48-b489-516bba1b3145", "b9e691a8-c0b8-4f89-a04d-d142b2b3e1b5", "57e80045-6b90-437c-bf65-871e8dec7235", "14e77065-cf2a-4a0b-826b-fc6c415c7776", "5904f64e-752a-4d64-9c17-0a126a6e4b97", "aa552291-ea2a-4467-bb86-8063f142b11e", "f29c1d98-93f8-4a72-bbe8-e38af65e0f28"], "befores": [{"name": "api_client", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\conftest.py\", line 142, in api_client\n    return ApiClient(config['url'])\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\api\\client.py\", line 12, in __init__\n    self._authorize()\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\api\\client.py\", line 30, in _authorize\n    res = self._request(\"POST\", location,\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\api\\client.py\", line 16, in _request\n    response = self.session.request(method, url, headers=headers, files=files, data=data, params=params)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\requests\\adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\n"}, "start": 1640018000998, "stop": 1640018001080}], "start": 1640018000998, "stop": 1640018278718}