{"uuid": "88472085-6fa5-42f3-a403-bb77d503d01a", "children": ["2b59567b-e981-45dc-9c86-6541f1809b87"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: New session attempts retry count exceeded\n\n", "trace": "  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 72, in driver\n    browser = get_driver(config, download_dir=temp_dir)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 53, in get_driver\n    browser = webdriver.Remote(selenoid, desired_capabilities=capabilities)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 359, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Init browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: New session attempts retry count exceeded\n\n", "trace": "  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 72, in driver\n    browser = get_driver(config, download_dir=temp_dir)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 53, in get_driver\n    browser = webdriver.Remote(selenoid, desired_capabilities=capabilities)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 359, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1640022712817, "stop": 1640023079348}], "start": 1640022712792, "stop": 1640023079443}], "start": 1640022712792, "stop": 1640023083074}