{"uuid": "244c463b-2924-4159-84af-8d99c3a69e52", "children": ["54697ac4-87d2-441c-8613-fd40a98ed5b7"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: session timed out or not found\n\n", "trace": "  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\tests\\ui_test\\base_ui.py\", line 43, in setup\n    self.login_page: LoginPage = request.getfixturevalue('login_page')\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 581, in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 601, in _get_active_fixturedef\n    self._compute_fixture_value(fixturedef)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 687, in _compute_fixture_value\n    fixturedef.execute(request=subrequest)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 1072, in execute\n    result = hook.pytest_fixture_setup(fixturedef=self, request=request)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\fixtures.py\", line 17, in login_page\n    return LoginPage(driver=driver)\n  File \"D:\\ProgrammingProjects\\PythonProj\\final_project\\vkidTest\\src\\ui\\pages\\base_page.py\", line 20, in __init__\n    self.driver.implicitly_wait(10)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1148, in implicitly_wait\n    self.execute(Command.SET_TIMEOUTS, {\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Anaconda3\\envs\\final_project\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1640018172624, "stop": 1640018196166}], "start": 1640018172624, "stop": 1640018197092}